[package]
name = "test-fuzz-macro"
version = "0.1.0-alpha.22"
edition = "2018"

description = "test-fuzz-macro"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/test-fuzz"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.0"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.73", features = ["full", "parsing", "visit-mut"] }
unzip-n = "0.1.2"

[features]
persistent = []
serde_bincode = []
serde_cbor = []
