[package]
name = "test-fuzz-macro"
version = "0.1.0"
edition = "2018"

description = "test-fuzz-macro"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/test-fuzz"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.0"
if_chain = "1.0.2"
lazy_static = "1.4.0"
proc-macro2 = "1.0.29"
quote = "1.0.9"
subprocess = "0.2.7"
syn = { version = "1.0.76", features = ["full", "parsing", "visit-mut"] }
toolchain_find = "0.2.0"
unzip-n = "0.1.2"

internal = { path = "../internal", package = "test-fuzz-internal", version = "=0.1.0" }

[features]
__persistent = []
__serde_bincode = ["internal/__serde_bincode"]
__serde_cbor = ["internal/__serde_cbor"]
