[package]
name = "test-fuzz-runtime"
version = "0.1.0-alpha.17"
edition = "2018"

description = "test-fuzz-runtime"

authors = ["Samuel E. Moelius III <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/test-fuzz"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
sha-1 = "0.9.6"

dirs = { path = "../dirs", package = "test-fuzz-dirs", version = "=0.1.0-alpha.17" }
