[package]
name = "test-fuzz-testing"
version = "3.0.1"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.56"
assert_cmd = "2.0.4"
cargo_metadata = "0.14.2"
if_chain = "1.0.2"
lazy_static = "1.4.0"
log = "0.4.16"
retry = "1.3.1"
subprocess = "0.2.8"

internal = { path = "../internal", package = "test-fuzz-internal", version = "=3.0.1" }
