[package]
name = "test-fuzz-testing"
version = "3.0.5"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.66"
assert_cmd = "2.0.5"
cargo_metadata = "0.15.1"
if_chain = "1.0.2"
lazy_static = "1.4.0"
log = "0.4.17"
retry = "2.0.0"
subprocess = "0.2.9"

internal = { path = "../internal", package = "test-fuzz-internal", version = "=3.0.5" }
